"""added public share fields

Revision ID: 32012c93ebdc
Revises: 1fbcae990556
Create Date: 2026-05-19 18:04:01.729689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32012c93ebdc'
down_revision = '1fbcae990556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.alter_column('share_token',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('share_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
